# Generated by Django 3.2.9 on 2021-11-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_grarueted',
            new_name='is_graduated',
        ),
    ]
